Repository boostcamp-2020/Project16-B-Account-Book, pull requests merged in 2020-11, with the labels that each got.

#4 [FE/BE] 환경설정 및 schema 설계
  .prettierrc
  client/package-lock.json
  client/package.json
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/controller/user.controller.js
  server/src/model/accountBook.model.js
  server/src/model/category.model.js
  server/src/model/transaction.model.js
  server/src/model/user.model.js
  server/src/route/user.route.js
Labels: 🎄 environment, 🎉 FE, 🎨 BE

#8 [FE/BE] 리팩토링 및 FE 구조 설계
  client/src/App.js
  client/src/App.jsx
  client/src/components/containers/LoginFormContainer.jsx
  client/src/components/presentational/LoginForm.jsx
  client/src/index.js
  client/src/index.jsx
  client/src/pages/AccountBookPage.jsx
  client/src/pages/AnalysisPage.jsx
  client/src/pages/CalendarPage.jsx
  client/src/pages/CategoryPage.jsx
  client/src/pages/DashboardPage.jsx
  client/src/pages/LoginPage.jsx
  client/src/pages/NotFoundPage.jsx
  client/src/pages/PaymentMethodPage.jsx
  client/src/pages/SettingPage.jsx
  client/src/pages/TransactionPage.jsx
  client/src/services/api.js
  client/src/slice.js
  client/src/store.js
  server/.env.sample
  server/src/.env.sample
  server/src/controller/user.controller.js
  server/src/service/user.service.js
  server/src/startup/db.js
Labels: 🎉 FE

#12 [FE] Dashboard page
  client/package-lock.json
  client/package.json
  client/src/components/containers/DashboardContainer.jsx
  client/src/components/presentational/DashboardPieChart.jsx
  client/src/components/presentational/DashboardVisualExpense.jsx
  client/src/pages/DashboardPage.jsx
  client/src/slice.js
  client/src/tempData.js
Labels: 🎉 FE

#13 [FE] Header 컴포넌트 구현
  client/.eslintrc.js
  client/public/color.js
  client/public/img/colored_logo_transparent_background.png
  client/public/img/dark_logo_only_transparent_background.png
  client/public/img/dark_logo_transparent_background.png
  client/public/img/dark_logo_white_background.jpg
  client/public/img/dark_title_transparent_background.png
  client/public/img/logo_only_transparent_background.png
  client/public/img/logo_transparent_background.png
  client/public/img/logo_white_background.jpg
  client/public/img/squirrel.jpeg
  client/public/img/title_transparent_background.png
  client/public/svg.js
  client/src/App.jsx
  client/src/components/containers/LoginFormContainer.jsx
  client/src/components/presentational/LoginForm.jsx
  client/src/components/presentational/common/Header.jsx
  client/src/components/presentational/common/Layout.jsx
  client/src/components/presentational/common/UserMenuDropDown.jsx
  client/src/index.jsx
  client/src/pages/LoginPage.jsx
  client/src/pages/NotFoundPage.jsx
  client/src/services/api.js
  client/src/slice.js
  client/webpack.config.js
Labels: 🎉 FE

#10 [FE] Sidebar 구현
  client/package-lock.json
  client/package.json
  client/public/color.js
  client/src/App.jsx
  client/src/components/presentational/common/Header.jsx
  client/src/components/presentational/common/SidebarList.jsx
  client/src/pages/AccountBookPage.jsx
  client/src/pages/AnalysisPage.jsx
  client/src/pages/CalendarPage.jsx
  client/src/pages/CategoryPage.jsx
  client/src/pages/DashboardPage.jsx
  client/src/pages/PaymentMethodPage.jsx
  client/src/pages/SettingPage.jsx
  client/src/pages/TransactionPage.jsx
  client/src/slice.js
  client/webpack.config.js
  server/src/service/user.service.js
Labels: 🎉 FE

#14 [FE] refactor: #9 Header & Sidebar 분리
  client/src/components/presentational/common/Header.jsx
  client/src/components/presentational/common/Sidebar.jsx
Labels: 🎉 FE

#15 [FE] Webpack config 기능 추가 및 수정
  client/.eslintrc.js
  client/src/App.jsx
  client/src/components/containers/DashboardContainer.jsx
  client/src/components/containers/LoginFormContainer.jsx
  client/src/components/presentational/DashboardPieChart.jsx
  client/src/components/presentational/DashboardVisualExpense.jsx
  client/src/components/presentational/LoginForm.jsx
  client/src/components/presentational/common/Header.jsx
  client/src/components/presentational/common/Layout.jsx
  client/src/components/presentational/common/SidebarList.jsx
  client/src/components/presentational/common/UserMenuDropDown.jsx
  client/src/index.jsx
  client/webpack.config.js
Labels: 🎄 environment, 🎉 FE

#16 반응형 UI 구현
  client/package-lock.json
  client/package.json
  client/public/color.js
  client/public/img/colored_logo_img.png
  client/public/img/dark_logo_title.png
  client/public/svg.js
  client/src/App.jsx
  client/src/components/presentational/common/Header.jsx
  client/src/components/presentational/common/Layout.jsx
  client/src/components/presentational/common/Overlay.jsx
  client/src/components/presentational/common/Sidebar.jsx
  client/src/components/presentational/common/SidebarModal.jsx
  client/src/components/presentational/common/UserMenuDropDown.jsx
  client/webpack.config.js
Labels: ⚒ fix, 🎉 FE

#17 hotfix: media query 관련 오류 수정
  client/src/components/presentational/common/Header.jsx
  client/src/components/presentational/common/Sidebar.jsx
  client/src/components/presentational/common/SidebarModal.jsx
Labels: ⚒ fix, 🎉 FE
