Repository boostcamp-2020/Project16-B-Account-Book, pull requests merged in 2020-12, with the labels that each got.

#28 [BE] 환경에 따라 사용하는 env 변경
  .gitignore
  server/.env.sample
  server/package.json
  server/src/app.js
Labels: 🎄 environment, 🎨 BE

#30 [BE] Transaction api 뼈대 및 GET /transaction route,controller,service 작성 및 테스트 작성
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/controller/transaction.controller.js
  server/src/controller/transaction.controller.test.js
  server/src/route/index.js
  server/src/route/transaction.route.js
  server/src/route/transaction.route.test.js
  server/src/service/__mocks__/transaction.service.js
  server/src/service/transaction.service.js
  server/src/service/transaction.service.test.js
Labels: :page_with_curl:대시보드, 🎨 BE

#31 [BE/FE] 카드/계좌 GET API 개발 & 페이지 구현
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/components/containers/PaymentContainer.jsx
  client/src/components/presentational/common/Sidebar.jsx
  client/src/components/presentational/payment/PaymentForm.jsx
  client/src/components/presentational/payment/PaymentItem.jsx
  client/src/pages/PaymentMethodPage.jsx
  client/src/services/api.js
  client/webpack.config.js
  server/src/controller/payment.controller.js
  server/src/route/index.js
  server/src/route/payment.route.js
  server/src/service/payment.service.js
Labels: 🎉 FE, 🎨 BE, 💳 카드/계좌

#34 [FE] Dashboard 페이지용 수입/지출 내역 추가 및 반응형 css 추가
  client/src/components/containers/DashboardContainer.jsx
  client/src/components/presentational/DashboardTextExpense.jsx
Labels: :page_with_curl:대시보드, 🎉 FE

#36 category/tag 페이지 UI 구현
  client/.eslintrc.js
  client/public/color.js
  client/public/icon.js
  client/src/App.jsx
  client/src/components/presentational/category_tag/Card.jsx
  client/src/components/presentational/category_tag/CardContainer.jsx
  client/src/components/presentational/category_tag/CategoryTagDummy.js
  client/src/components/presentational/category_tag/Navigation.jsx
  client/src/components/presentational/category_tag/NavigationMarker.jsx
  client/src/components/presentational/common/DropDown.jsx
  client/src/components/presentational/common/Layout.jsx
  client/src/pages/CategoryPage.jsx
  client/src/pages/CategoryTagPage.jsx
Labels: 🎉 FE, 🏷️ 카테고리/태그

#38 [FE] Dashboard responsive
  client/src/components/containers/DashboardContainer.jsx
  client/src/components/presentational/dashboard/DashboardPieChart.jsx
  client/src/components/presentational/dashboard/DashboardTextExpense.jsx
  client/src/components/presentational/dashboard/DashboardVisualExpense.jsx
Labels: :page_with_curl:대시보드, 🎉 FE

#40 [BE/FE] 카드/계좌 추가 및 삭제 기능 구현
  client/src/components/containers/PaymentContainer.jsx
  client/src/components/presentational/common/DropDown.jsx
  client/src/components/presentational/payment/AddButton.jsx
  client/src/components/presentational/payment/ItemMetadata.jsx
  client/src/components/presentational/payment/PaymentForm.jsx
  client/src/components/presentational/payment/PaymentItem.jsx
  client/src/components/presentational/payment/PaymentModal.js
  client/src/services/api.js
  client/src/slice.js
  client/webpack.config.js
  server/src/controller/payment.controller.js
  server/src/route/payment.route.js
  server/src/service/payment.service.js
Labels: 🎉 FE, 🎨 BE, 💳 카드/계좌

#42 [FE] fix: 코드리뷰 반영
  client/src/components/presentational/common/DropDown.jsx
Labels: ⚒ fix

#41 Category/Tag 관련 API 작성
  client/package-lock.json
  client/package.json
  client/src/components/presentational/category_tag/Card.jsx
  server/src/controller/accountBook.controller.js
  server/src/controller/category.controller.js
  server/src/controller/payment.controller.js
  server/src/controller/transaction.controller.js
  server/src/route/accountBook.route.js
  server/src/route/category.route.js
  server/src/route/index.js
  server/src/service/accountBook.service.js
  server/src/service/category.service.js
  server/src/service/payment.service.js
  server/src/service/transaction.service.js
  server/src/util/error.js
Labels: 🎨 BE, 🏷️ 카테고리/태그

#48 [BE] Oauth 로그인 및 JwtToken validator 미들웨어
  server/babel.config.js
  server/middleware/githubOAuth.js
  server/middleware/naverOAuth.js
  server/middleware/tokenValidator.js
  server/package-lock.json
  server/package.json
  server/src/controller/user.controller.js
  server/src/model/user.model.js
  server/src/route/index.js
  server/src/route/user.route.js
  server/src/service/user.service.js
  server/src/util/jwtToken.util.js
Labels: :lock: authorization, 🎨 BE

#49 [FE/BE] 카드/계좌 수정 및 코드 리팩토링
  client/src/components/containers/PaymentContainer.jsx
  client/src/components/presentational/common/DropDown.jsx
  client/src/components/presentational/payment/ItemMetadata.jsx
  client/src/components/presentational/payment/PaymentForm.jsx
  client/src/components/presentational/payment/PaymentItem.jsx
  client/src/components/presentational/payment/PaymentModal.js
  client/src/components/presentational/payment/cardEvent.jsx
  client/src/services/api.js
  client/src/services/swalFormat.js
  client/src/slice.js
  server/src/controller/payment.controller.js
  server/src/route/payment.route.js
  server/src/service/payment.service.js
Labels: 🎉 FE, 🎨 BE, 💳 카드/계좌

#50 [FE] util/axios 추가
  client/package.json
  client/util/axios.js
  client/util/token.js
  client/webpack.config.js
  server/src/controller/accountBook.controller.js
Labels: 🎄 environment, 🎉 FE

#52 [FE] login 기능 (OAuth)
  client/package-lock.json
  client/package.json
  client/src/components/containers/LoginFormContainer.jsx
  client/src/services/api.js
  client/src/slice.js
  client/src/svgs/GitHubSvg.js
  client/src/svgs/NaverSvg.js
Labels: :lock: authorization, 🎉 FE

#54 [FE] category/tag 페이지 드랍다운 메뉴에 대한 이벤트 구현중
  client/src/components/presentational/category_tag/CardContainer.jsx
  client/src/components/presentational/category_tag/CardDropDown.jsx
  client/src/components/presentational/category_tag/CategoryCard.jsx
  client/src/components/presentational/category_tag/TagCard.jsx
  client/src/pages/CategoryTagPage.jsx
  client/src/services/api.js
  client/src/slice.js
  client/util/axios.js
  client/util/token.js
  server/src/controller/accountBook.controller.js
  server/src/model/accountBook.model.js
  server/src/service/accountBook.service.js
Labels: 🎉 FE, 🏷️ 카테고리/태그

#62 [FE] Transaction CRUD
  client/src/components/containers/TransactionContainer.jsx
  client/src/components/presentational/transaction/TransactionInputForm.jsx
  client/src/components/presentational/transaction/TransactionList.jsx
  client/src/pages/TransactionPage.jsx
  client/src/services/api.js
  client/src/slice.js
Labels: :dollar: transaction, 🎉 FE

#63 [BE] Transaction CRUD API
  server/middleware/tokenValidator.js
  server/src/controller/transaction.controller.js
  server/src/route/transaction.route.js
  server/src/service/transaction.service.js
Labels: :dollar: transaction, 🎨 BE

#64 [BE/FE] 카드 별 수입/지출 내역 시각화
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/containers/PaymentContainer.jsx
  client/src/components/containers/PaymentDetailContainer.jsx
  client/src/components/presentational/payment/AddButton.jsx
  client/src/components/presentational/payment/ItemMetadata.jsx
  client/src/components/presentational/payment/detail/DetailButton.jsx
  client/src/components/presentational/payment/detail/DetailForm.jsx
  client/src/pages/PaymentDetailPage.jsx
  client/src/paymentSlice.js
  client/src/services/api.js
  client/src/services/paymentAPI.js
  client/src/slice.js
  client/util/axios.js
  client/util/token.js
  client/webpack.config.js
  server/src/controller/payment.controller.js
  server/src/route/payment.route.js
  server/src/service/payment.service.js
Labels: 🎉 FE, 🎨 BE, 💳 카드/계좌

#65 Tag 페이지 기본기능 구현
  client/public/icon.js
  client/src/components/containers/TagContainer.jsx
  client/src/components/presentational/category_tag/CardContainer.jsx
  client/src/components/presentational/category_tag/CardList.jsx
  client/src/components/presentational/category_tag/CategoryCard.jsx
  client/src/components/presentational/category_tag/CategoryTagDummy.js
  client/src/components/presentational/category_tag/Navigation.jsx
  client/src/components/presentational/category_tag/TagCard.jsx
  client/src/components/presentational/category_tag/categories.js
  client/src/pages/CategoryTagPage.jsx
  client/src/services/api.js
  client/src/slice.js
  server/src/app.js
  server/src/controller/accountBook.controller.js
  server/src/route/accountBook.route.js
  server/src/service/accountBook.service.js
Labels: 🎉 FE, 🎨 BE, 🏷️ 카테고리/태그

#68 category/tag 페이지 수정
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/containers/TagContainer.jsx
  client/src/components/presentational/category_tag/CardList.jsx
  client/src/components/presentational/category_tag/Navigation.jsx
  client/src/components/presentational/category_tag/TagCard.jsx
  client/src/components/presentational/common/Layout.jsx
  client/src/pages/CategoryTagPage.jsx
  client/src/services/api.js
  client/src/slice.js
  client/util/axios.js
  server/src/controller/accountBook.controller.js
  server/src/route/accountBook.route.js
  server/src/service/accountBook.service.js
Labels: ⚒ fix, 🎉 FE, 🏷️ 카테고리/태그

#69 [FE/BE] 카드/계좌 상세 페이지 - 수입, 지출 그래프 구현
  client/src/components/containers/PaymentContainer.jsx
  client/src/components/containers/PaymentDetailContainer.jsx
  client/src/components/presentational/payment/detail/DetailForm.jsx
  client/src/paymentSlice.js
  client/src/services/paymentAPI.js
  client/src/slice.js
  client/util/axios.js
  client/webpack.config.js
  server/src/controller/payment.controller.js
  server/src/model/transaction.model.js
  server/src/route/payment.route.js
  server/src/service/payment.service.js
Labels: 🎉 FE, 🎨 BE, 💳 카드/계좌

#75 [FE] fab 사용 해서 내역 추가 및 수정 모달 띄우기 및 삭제 체크박스 띄우기
  client/src/components/containers/TransactionContainer.jsx
  client/src/components/presentational/transaction/TransactionFab.jsx
  client/src/components/presentational/transaction/TransactionInputForm.jsx
  client/src/components/presentational/transaction/TransactionList.jsx
  client/src/components/presentational/transaction/TransactionModal.jsx
  client/src/services/api.js
  client/src/slice.js
  server/src/controller/accountBook.controller.js
  server/src/controller/transaction.controller.js
  server/src/service/transaction.service.js
Labels: :page_with_curl:대시보드, ⚒ fix, ✨ enhancement, 🎉 FE

#76 [FE/BE] 카드/계좌 상세 페이지 - 필터링 기능 추가
  client/src/components/containers/PaymentDetailContainer.jsx
  client/src/components/presentational/payment/detail/DetailDropdown.jsx
  client/src/components/presentational/payment/detail/DetailForm.jsx
  client/src/components/presentational/payment/detail/SetDateList.js
  client/src/services/paymentAPI.js
  client/src/slice.js
  server/src/controller/payment.controller.js
  server/src/route/payment.route.js
  server/src/service/payment.service.js
Labels: 🎉 FE, 🎨 BE, 💳 카드/계좌

#77 [FE] calendar 페이지 디자인 진행
  client/public/index.html
  client/src/components/containers/CalendarContainer.jsx
  client/src/components/presentational/calendar/CalendarForm.jsx
  client/src/pages/CalendarPage.jsx
  client/src/slice.js
Labels: 🎉 FE, 📆 캘린더

#78 가계부 선택 페이지 구현(진행중)
  client/public/icon.js
  client/src/App.jsx
  client/src/components/containers/AccountBookContainer.jsx
  client/src/components/containers/TagContainer.jsx
  client/src/components/presentational/accountbook/AccountBookCard.jsx
  client/src/components/presentational/accountbook/AccountBookList.jsx
  client/src/components/presentational/accountbook/CardLabel.jsx
  client/src/components/presentational/common/SidebarList.jsx
  client/src/pages/AccountBookPage.jsx
  client/src/services/api.js
  client/src/slice.js
  client/util/axios.js
  client/util/color.js
  client/util/cookie.js
  client/webpack.config.js
  server/middleware/tokenValidator.js
  server/src/controller/accountBook.controller.js
  server/src/route/accountBook.route.js
  server/src/route/index.js
Labels: :books:가계부, ⚒ fix, 🎉 FE, 🎨 BE

#80 [BE/FE] Calendar 페이지 구현
  client/src/components/containers/CalendarContainer.jsx
  client/src/components/containers/PaymentDetailContainer.jsx
  client/src/components/presentational/calendar/CalendarForm.jsx
  client/src/components/presentational/calendar/CalendarUtil.js
  client/src/components/presentational/calendar/MakeTemplate.js
  client/src/components/presentational/payment/detail/SetDateList.js
  client/src/services/api.js
  client/src/slice.js
  client/util/axios.js
  server/src/controller/accountBook.controller.js
  server/src/controller/transaction.controller.js
  server/src/route/transaction.route.js
  server/src/service/transaction.service.js
Labels: 🎉 FE, 🎨 BE, 📆 캘린더

#82 [FE] Sms parser
  client/.babelrc
  client/package-lock.json
  client/package.json
  client/util/smsParser.js
  client/util/smsParser.test.js
Labels: :dollar: transaction, 🎉 FE

#83 가계부 선택 페이지 기능 완성 및 애니메이션 적용
  client/public/icon.js
  client/src/components/containers/AccountBookContainer.jsx
  client/src/components/presentational/accountbook/AccountBookCard.jsx
  client/src/components/presentational/accountbook/AccountBookList.jsx
  client/src/components/presentational/accountbook/AddModal.jsx
  client/src/components/presentational/accountbook/CardLabel.jsx
  client/src/components/presentational/accountbook/Overlay.jsx
  client/src/services/api.js
  client/src/slice.js
  client/util/axios.js
  client/util/color.js
  server/src/controller/accountBook.controller.js
Labels: :books:가계부, ⚒ fix, 🎉 FE

#86 [FE] Authorization
  client/.babelrc
  client/src/App.jsx
  client/src/components/containers/LoginFormContainer.jsx
  client/src/components/presentational/LoginForm.jsx
  client/src/components/presentational/common/Header.jsx
  client/src/components/presentational/common/UserMenuDropDown.jsx
  client/src/components/presentational/transaction/TransactionInputForm.jsx
  client/src/pages/NotFoundPage.jsx
  client/src/slice.js
  server/src/controller/user.controller.js
Labels: :lock: authorization, 🎉 FE

#87 [FE] Calendar 페이지 리팩토링 & 체크박스 구현
  client/src/components/containers/CalendarContainer.jsx
  client/src/components/presentational/calendar/CalendarCheckbox.jsx
  client/src/components/presentational/calendar/CalendarForm.jsx
  client/src/components/presentational/calendar/MakeTemplate.js
  client/src/components/presentational/calendar/TypeTemplate.js
  client/src/components/presentational/calendar/style.js
  client/src/components/presentational/payment/detail/DetailDropdown.jsx
  client/util/axios.js
Labels: 🎉 FE, 📆 캘린더

#94 [FE/BE] settings 페이지 (구현 중)
  client/src/components/containers/SettingContainer.jsx
  client/src/components/presentational/payment/AddButton.jsx
  client/src/components/presentational/payment/PaymentForm.jsx
  client/src/components/presentational/payment/detail/DetailDropdown.jsx
  client/src/components/presentational/payment/detail/DetailForm.jsx
  client/src/components/presentational/setting/SettingEditor.jsx
  client/src/components/presentational/setting/SettingHeader.jsx
  client/src/components/presentational/setting/SettingPreview.jsx
  client/src/pages/SettingPage.jsx
  client/src/services/userAPI.js
  client/src/slice.js
  server/src/controller/user.controller.js
  server/src/route/index.js
  server/src/route/user.route.js
  server/src/service/user.service.js
Labels: ⚙ 셋팅, 🎉 FE, 🎨 BE

#95 [FE] 가계부 선택 페이지 UI 개선 / 보고서 페이지 구현(진행중)
  client/src/components/containers/AccountBookContainer.jsx
  client/src/components/containers/AnalysisContainer.jsx
  client/src/components/presentational/accountbook/AccountBookCard.jsx
  client/src/components/presentational/accountbook/AccountBookList.jsx
  client/src/components/presentational/analysis/AnalysisDate.jsx
  client/src/components/presentational/analysis/AnalysisForm.jsx
  client/src/components/presentational/analysis/CumulativeAnalysis.jsx
  client/src/components/presentational/analysis/CumulativeExpenditure.jsx
  client/src/pages/AnalysisPage.jsx
  client/src/services/api.js
  client/src/slice.js
  client/util/transaction.js
  server/src/controller/transaction.controller.js
  server/src/route/transaction.route.js
  server/src/service/transaction.service.js
Labels: ⚒ fix, 🎉 FE, 📑보고서

#96 [FE/BE] Transaction page
  client/public/icon.js
  client/src/components/containers/TransactionContainer.jsx
  client/src/components/presentational/transaction/ParserInputForm.jsx
  client/src/components/presentational/transaction/TransactionFab.jsx
  client/src/components/presentational/transaction/TransactionInputForm.jsx
  client/src/components/presentational/transaction/TransactionModal.jsx
  client/src/services/api.js
  server/src/controller/transaction.controller.js
  server/src/route/transaction.route.js
  server/src/service/transaction.service.js
Labels: :dollar: transaction, ✨ enhancement, 🎉 FE, 🎨 BE

#97 [FE] Calendar 리팩토링
  client/src/components/containers/CalendarContainer.jsx
  client/src/components/presentational/calendar/CalendarUtil.js
  client/src/components/presentational/calendar/MakeTemplate.js
  client/src/components/presentational/payment/detail/SetDateList.js
  client/src/slice.js
Labels: 🎉 FE, 📆 캘린더

#99 [FE] categories 항목 추가
  client/src/components/presentational/category_tag/categories.js
Labels: 🎉 FE, 🏷️ 카테고리/태그

#100 [FE] Dashboard fix
  client/src/components/containers/AccountBookContainer.jsx
  client/src/components/containers/DashboardContainer.jsx
  client/src/components/presentational/dashboard/DashboardPieChart.jsx
  client/src/components/presentational/dashboard/DashboardTextExpense.jsx
Labels: :page_with_curl:대시보드, 🎉 FE

#102 [BE/FE] 가계부 설정 페이지 (구현 중)
  client/public/img/default_image.png
  client/src/App.jsx
  client/src/components/containers/SettingContainer.jsx
  client/src/components/presentational/accountbook/AccountBookList.jsx
  client/src/components/presentational/calendar/style.js
  client/src/components/presentational/payment/AddButton.jsx
  client/src/components/presentational/payment/PaymentForm.jsx
  client/src/components/presentational/payment/detail/DetailDropdown.jsx
  client/src/components/presentational/payment/detail/DetailForm.jsx
  client/src/components/presentational/setting/SettingEditor.jsx
  client/src/components/presentational/setting/SettingHeader.jsx
  client/src/components/presentational/setting/SettingPreview.jsx
  client/src/components/presentational/setting/button/Button.jsx
  client/src/components/presentational/setting/form/CardEditForm.jsx
  client/src/components/presentational/setting/form/CardForm.jsx
  client/src/services/api.js
  client/src/services/userAPI.js
  client/src/slice.js
  server/src/controller/transaction.controller.js
  server/src/controller/user.controller.js
  server/src/route/user.route.js
  server/src/service/user.service.js
Labels: ⚙ 셋팅, 🎉 FE, 🎨 BE

#105 보고서 페이지 추가 기능 구현 및 UI 개선
  client/public/icon.js
  client/src/components/containers/AccountBookContainer.jsx
  client/src/components/presentational/analysis/AnalysisDate.jsx
  client/src/components/presentational/analysis/AnalysisForm.jsx
  client/src/components/presentational/analysis/CumulativeAnalysis.jsx
  client/src/components/presentational/analysis/CumulativeExpenditure.jsx
  client/src/components/presentational/analysis/TopCard.jsx
  client/util/axios.js
  server/middleware/cookieParser.js
  server/src/controller/accountBook.controller.js
  server/src/controller/transaction.controller.js
  server/src/controller/user.controller.js
  server/src/route/index.js
  server/src/route/transaction.route.js
Labels: ⚒ fix, 🎉 FE, 🎨 BE, 📑보고서

#108 Env hot-fix
  client/.babelrc
  server/package.json
Labels: 🎄 environment, 🎉 FE, 🎨 BE

#111 [FE/BE] settings 페이지 : 가계부 Master 설정, 가계부 Member 초대하기/내보내기 기능 구현
  client/public/index.html
  client/src/components/containers/SettingContainer.jsx
  client/src/components/presentational/payment/PaymentModal.js
  client/src/components/presentational/setting/SettingEditor.jsx
  client/src/components/presentational/setting/button/Button.jsx
  client/src/components/presentational/setting/button/InviteButton.jsx
  client/src/components/presentational/setting/form/CardEditForm.jsx
  client/src/components/presentational/setting/modal/DeleteModalForm.jsx
  client/src/components/presentational/setting/modal/InviteModal.jsx
  client/src/components/presentational/setting/modal/ModalContents.jsx
  client/src/components/presentational/setting/modal/ModalForm.jsx
  client/src/services/api.js
  client/src/services/userAPI.js
  client/src/slice.js
  server/src/controller/transaction.controller.js
  server/src/controller/user.controller.js
  server/src/route/user.route.js
  server/src/service/user.service.js
Labels: ⚙ 셋팅, 🎉 FE, 🎨 BE

#113 Transaction enhancement
  client/src/components/presentational/dashboard/DashboardTextExpense.jsx
  client/src/components/presentational/transaction/BulkInputForm.jsx
  client/src/components/presentational/transaction/TransactionInputForm.jsx
  client/src/components/presentational/transaction/TransactionLineChart.jsx
  client/src/components/presentational/transaction/TransactionList.jsx
  client/util/currencyExchange.js
Labels: :dollar: transaction, ✨ enhancement, 🎉 FE

#117 [Merge] dev -> master
  .github/workflows/node.js.yml
  README.md
  client/.babelrc
  client/public/icon.js
  client/public/index.html
  client/src/components/containers/SettingContainer.jsx
  client/src/components/presentational/dashboard/DashboardTextExpense.jsx
  client/src/components/presentational/payment/PaymentModal.js
  client/src/components/presentational/setting/SettingEditor.jsx
  client/src/components/presentational/setting/button/Button.jsx
  client/src/components/presentational/setting/button/InviteButton.jsx
  client/src/components/presentational/setting/form/CardEditForm.jsx
  client/src/components/presentational/setting/modal/DeleteModalForm.jsx
  client/src/components/presentational/setting/modal/InviteModal.jsx
  client/src/components/presentational/setting/modal/ModalContents.jsx
  client/src/components/presentational/setting/modal/ModalForm.jsx
  client/src/components/presentational/transaction/BulkInputForm.jsx
  client/src/components/presentational/transaction/TransactionFab.jsx
  client/src/components/presentational/transaction/TransactionInputForm.jsx
  client/src/components/presentational/transaction/TransactionLineChart.jsx
  client/src/components/presentational/transaction/TransactionList.jsx
  client/src/components/presentational/transaction/TransactionModal.jsx
  client/src/pages/NotFoundPage.jsx
  client/src/services/api.js
  client/src/services/userAPI.js
  client/src/slice.js
  client/util/currencyExchange.js
  server/package.json
  server/src/controller/transaction.controller.js
  server/src/controller/user.controller.js
  server/src/route/user.route.js
  server/src/service/user.service.js
Labels: 🎉 FE, 🎨 BE

#119 [FE] 프로필 사진 업로드 & 취소, 로딩 스피너 구현 / 로그인 페이지 디자인
  client/.env.sample
  client/src/components/containers/SettingContainer.jsx
  client/src/components/presentational/LoginForm.jsx
  client/src/components/presentational/common/UserMenuDropDown.jsx
  client/src/components/presentational/setting/SettingEditor.jsx
  client/src/components/presentational/setting/button/Button.jsx
  client/src/components/presentational/setting/form/CardEditForm.jsx
  client/src/components/presentational/setting/modal/InviteModal.jsx
  client/src/components/presentational/setting/modal/ModalContents.jsx
  client/src/components/presentational/setting/uploader/ImageFileInput.jsx
  client/src/services/imageUploader.js
  client/src/slice.js
  server/middleware/kakaoOAuth.js
Labels: ⚙ 셋팅, 🎉 FE

#125 [FE] Refactor - transaction slice
  client/src/components/containers/AccountBookContainer.jsx
  client/src/components/containers/AnalysisContainer.jsx
  client/src/components/containers/CalendarContainer.jsx
  client/src/components/containers/DashboardContainer.jsx
  client/src/components/containers/LoginFormContainer.jsx
  client/src/components/containers/PaymentContainer.jsx
  client/src/components/containers/PaymentDetailContainer.jsx
  client/src/components/containers/SettingContainer.jsx
  client/src/components/containers/TagContainer.jsx
  client/src/components/containers/TransactionContainer.jsx
  client/src/components/presentational/category_tag/TagCard.jsx
  client/src/components/presentational/common/Header.jsx
  client/src/components/presentational/transaction/BulkInputForm.jsx
  client/src/components/presentational/transaction/ParserInputForm.jsx
  client/src/components/presentational/transaction/TransactionDate.jsx
  client/src/components/presentational/transaction/TransactionFab.jsx
  client/src/components/presentational/transaction/TransactionInputForm.jsx
  client/src/components/presentational/transaction/TransactionList.jsx
  client/src/components/presentational/transaction/TransactionModal.jsx
  client/src/store.js
  client/src/transactionSlice.js
  client/util/transaction.js
Labels: 🎉 FE

#126 [FE] slice 파일 분리 & 일부 페이지 리팩토링
  client/src/PaymentSlice.js
  client/src/calendarSlice.js
  client/src/components/containers/CalendarContainer.jsx
  client/src/components/containers/PaymentContainer.jsx
  client/src/components/containers/PaymentDetailContainer.jsx
  client/src/components/containers/SettingContainer.jsx
  client/src/components/presentational/common/UserMenuDropDown.jsx
  client/src/components/presentational/setting/SettingEditor.jsx
  client/src/components/presentational/setting/form/CardEditForm.jsx
  client/src/components/presentational/setting/modal/InviteModal.jsx
  client/src/components/presentational/setting/uploader/ImageFileInput.jsx
  client/src/settingSlice.js
  client/src/slice.js
  client/src/store.js
  client/webpack.config.js
  client/webpack.prod.config.js
Labels: 🎉 FE

#127 [FE] Hotfixes
  client/src/components/containers/DashboardContainer.jsx
  client/src/components/presentational/dashboard/Category.jsx
  client/src/components/presentational/dashboard/CategorySection.jsx
  client/src/components/presentational/dashboard/ComparisonAnaysisSection.jsx
  client/src/components/presentational/transaction/ArrowPointer.jsx
  client/src/components/presentational/transaction/TransactionInputForm.jsx
  client/src/components/presentational/transaction/TransactionList.jsx
Labels: :dollar: transaction, 🎉 FE

#128 코드 수정 진행중
  client/public/icon.js
  server/src/model/accountBook.model.js
Labels: ⚒ fix

#129 [FE] fix: 카테고리/태그 중 한 가지 기준으로 filter 되도록 수정
  client/src/components/presentational/analysis/AnalysisForm.jsx
  client/src/components/presentational/analysis/Checkboxes.jsx
Labels: ⚒ fix, 🎉 FE

#130 merge dev branch for production
  client/public/icon.js
  client/src/calendarSlice.js
  client/src/components/containers/AccountBookContainer.jsx
  client/src/components/containers/AnalysisContainer.jsx
  client/src/components/containers/CalendarContainer.jsx
  client/src/components/containers/DashboardContainer.jsx
  client/src/components/containers/LoginFormContainer.jsx
  client/src/components/containers/PaymentContainer.jsx
  client/src/components/containers/PaymentDetailContainer.jsx
  client/src/components/containers/SettingContainer.jsx
  client/src/components/containers/TagContainer.jsx
  client/src/components/containers/TransactionContainer.jsx
  client/src/components/presentational/analysis/AnalysisForm.jsx
  client/src/components/presentational/analysis/Checkboxes.jsx
  client/src/components/presentational/category_tag/TagCard.jsx
  client/src/components/presentational/common/Header.jsx
  client/src/components/presentational/common/UserMenuDropDown.jsx
  client/src/components/presentational/dashboard/Category.jsx
  client/src/components/presentational/dashboard/CategorySection.jsx
  client/src/components/presentational/dashboard/ComparisonAnaysisSection.jsx
  client/src/components/presentational/setting/SettingEditor.jsx
  client/src/components/presentational/setting/form/CardEditForm.jsx
  client/src/components/presentational/setting/modal/InviteModal.jsx
  client/src/components/presentational/setting/uploader/ImageFileInput.jsx
  client/src/components/presentational/transaction/ArrowPointer.jsx
  client/src/components/presentational/transaction/BulkInputForm.jsx
  client/src/components/presentational/transaction/ParserInputForm.jsx
  client/src/components/presentational/transaction/TransactionDate.jsx
  client/src/components/presentational/transaction/TransactionFab.jsx
  client/src/components/presentational/transaction/TransactionInputForm.jsx
  client/src/components/presentational/transaction/TransactionList.jsx
  client/src/components/presentational/transaction/TransactionModal.jsx
  client/src/paymentSlice.js
  client/src/settingSlice.js
  client/src/slice.js
  client/src/store.js
  client/src/transactionSlice.js
  client/util/transaction.js
  client/webpack.config.js
  client/webpack.prod.config.js
  server/src/model/accountBook.model.js
Labels: 배포

#131 [FE] fix: 거래내역 월 선택 기준 수정
  client/util/transaction.js
Labels: ⚒ fix, 🎉 FE

#132 [FE] fix: filter 오류 수정
  client/src/components/presentational/analysis/AnalysisForm.jsx
Labels: ⚒ fix, 🎉 FE

#135 [FE] setting & calendar 페이지 - User가 선택한 시작 요일에 따른 calendar 변경
  client/src/components/containers/CalendarContainer.jsx
  client/src/components/presentational/calendar/CalendarForm.jsx
  client/src/components/presentational/calendar/CalendarUtil.js
  client/src/components/presentational/calendar/CalendarWeekDays.jsx
  client/src/components/presentational/calendar/MakeTemplate.js
  client/src/components/presentational/payment/AddButton.jsx
  client/src/components/presentational/payment/PaymentForm.jsx
  client/src/components/presentational/payment/PaymentModal.js
  client/src/components/presentational/payment/detail/DetailForm.jsx
  client/src/components/presentational/setting/form/CardEditForm.jsx
  client/src/components/presentational/setting/form/CardForm.jsx
  client/src/components/presentational/setting/modal/InviteModal.jsx
  client/src/components/presentational/setting/uploader/ImageFileInput.jsx
  client/util/bulk_insert/DescriptionExample.json
  client/util/bulk_insert/Expenditure_Transaction.csv
  client/util/bulk_insert/Income_Transaction.csv
  client/util/bulk_insert/expenditureTransaction.py
  client/util/bulk_insert/incomeTransaction.py
Labels: ⚙ 셋팅, 🎉 FE, 📆 캘린더

#136 [FE] CSV 예외처리 보강 및 대시보드 가이드라인 수정
  client/src/components/containers/DashboardContainer.jsx
  client/src/components/presentational/category_tag/categories.js
  client/src/components/presentational/dashboard/Category.jsx
  client/src/components/presentational/dashboard/GuideLine.jsx
  client/src/components/presentational/transaction/ArrowPointer.jsx
  client/src/components/presentational/transaction/BulkInputForm.jsx
  client/src/components/presentational/transaction/CSVInputForm.jsx
  client/src/components/presentational/transaction/TransactionInputForm.jsx
  client/src/components/presentational/transaction/TransactionModal.jsx
  client/util/formatter.js
Labels: ⚒ fix, 🎉 FE

#137 태그 수정/삭제 관련 오류수정 + 내역보기 모달 추가 + icon 추가
  client/public/icon.js
  client/src/components/containers/TagContainer.jsx
  client/src/components/containers/TransactionContainer.jsx
  client/src/components/presentational/accountbook/AddModal.jsx
  client/src/components/presentational/accountbook/Overlay.jsx
  client/src/components/presentational/analysis/CumulativeAnalysis.jsx
  client/src/components/presentational/category_tag/CardList.jsx
  client/src/components/presentational/category_tag/CategoryCard.jsx
  client/src/components/presentational/category_tag/TagCard.jsx
  client/src/components/presentational/category_tag/TransactionModal.jsx
  client/src/components/presentational/category_tag/categories.js
  client/src/components/presentational/transaction/TransactionInputForm.jsx
  client/src/components/presentational/transaction/TransactionList.jsx
  client/src/services/api.js
  client/src/services/tagAPI.js
  client/src/slice.js
  client/src/store.js
  client/src/tagSlice.js
  server/src/controller/category.controller.js
  server/src/controller/transaction.controller.js
  server/src/route/category.route.js
  server/src/route/index.js
  server/src/route/transaction.route.js
  server/src/service/category.service.js
  server/src/service/transaction.service.js
Labels: ⚒ fix, 🎉 FE, 🏷️ 카테고리/태그, 🐛 bug

#138 [BE] fix: 태그명 관련 예외처리
  server/src/controller/accountBook.controller.js
Labels: ⚒ fix

#139 [FE] refactor: 자잘한 디자인 수정
  client/src/components/presentational/LoginForm.jsx
  client/src/components/presentational/common/UserMenuDropDown.jsx
Labels: 🎉 FE

#140 [FE] fix: Hot fix
  README.md
  client/src/components/presentational/transaction/ParserInputForm.jsx
  client/src/components/presentational/transaction/TransactionInputForm.jsx
  client/util/formatter.js
  workflow.drawio
  서비스 흐름도.png
Labels: 🎉 FE

#141 [BE] fix: 태그명 관련 예외처리 추가
  server/src/controller/accountBook.controller.js
Labels: ⚒ fix

#142 [FE] 스키마 필드 수정
  client/src/components/containers/DashboardContainer.jsx
  server/src/model/transaction.model.js
Labels: 🎉 FE

#143 [FE] fix: pie chart label missing
  client/src/components/presentational/dashboard/DashboardPieChart.jsx
Labels: ⚒ fix, 🎉 FE

#144 merge dev branch -> master branch
  README.md
  client/public/icon.js
  client/src/components/containers/CalendarContainer.jsx
  client/src/components/containers/DashboardContainer.jsx
  client/src/components/containers/TagContainer.jsx
  client/src/components/containers/TransactionContainer.jsx
  client/src/components/presentational/LoginForm.jsx
  client/src/components/presentational/accountbook/AddModal.jsx
  client/src/components/presentational/accountbook/Overlay.jsx
  client/src/components/presentational/analysis/CumulativeAnalysis.jsx
  client/src/components/presentational/calendar/CalendarForm.jsx
  client/src/components/presentational/calendar/CalendarUtil.js
  client/src/components/presentational/calendar/CalendarWeekDays.jsx
  client/src/components/presentational/calendar/MakeTemplate.js
  client/src/components/presentational/category_tag/CardList.jsx
  client/src/components/presentational/category_tag/CategoryCard.jsx
  client/src/components/presentational/category_tag/TagCard.jsx
  client/src/components/presentational/category_tag/TransactionModal.jsx
  client/src/components/presentational/category_tag/categories.js
  client/src/components/presentational/common/UserMenuDropDown.jsx
  client/src/components/presentational/dashboard/Category.jsx
  client/src/components/presentational/dashboard/DashboardPieChart.jsx
  client/src/components/presentational/dashboard/GuideLine.jsx
  client/src/components/presentational/payment/AddButton.jsx
  client/src/components/presentational/payment/PaymentForm.jsx
  client/src/components/presentational/payment/PaymentModal.js
  client/src/components/presentational/payment/detail/DetailForm.jsx
  client/src/components/presentational/setting/form/CardEditForm.jsx
  client/src/components/presentational/setting/form/CardForm.jsx
  client/src/components/presentational/setting/modal/InviteModal.jsx
  client/src/components/presentational/setting/uploader/ImageFileInput.jsx
  client/src/components/presentational/transaction/ArrowPointer.jsx
  client/src/components/presentational/transaction/BulkInputForm.jsx
  client/src/components/presentational/transaction/CSVInputForm.jsx
  client/src/components/presentational/transaction/ParserInputForm.jsx
  client/src/components/presentational/transaction/TransactionInputForm.jsx
  client/src/components/presentational/transaction/TransactionList.jsx
  client/src/components/presentational/transaction/TransactionModal.jsx
  client/src/services/api.js
  client/src/services/tagAPI.js
  client/src/slice.js
  client/src/store.js
  client/src/tagSlice.js
  client/util/bulk_insert/DescriptionExample.json
  client/util/bulk_insert/Expenditure_Transaction.csv
  client/util/bulk_insert/Income_Transaction.csv
  client/util/bulk_insert/expenditureTransaction.py
  client/util/bulk_insert/incomeTransaction.py
  client/util/formatter.js
  server/src/controller/accountBook.controller.js
  server/src/controller/category.controller.js
  server/src/controller/transaction.controller.js
  server/src/model/transaction.model.js
  server/src/route/category.route.js
  server/src/route/index.js
  server/src/route/transaction.route.js
  server/src/service/category.service.js
  server/src/service/transaction.service.js
  workflow.drawio
  서비스 흐름도.png
Labels: 배포

#145 [FE] fix: sms 파서 수정
  client/src/components/presentational/transaction/ParserInputForm.jsx
  client/src/components/presentational/transaction/TransactionInputForm.jsx
  client/src/transactionSlice.js
  client/util/smsParser.js
  server/src/controller/transaction.controller.js
Labels: ⚒ fix, 🎉 FE
